// https://nuxt.com/docs/api/configuration/nuxt-config

export default defineNuxtConfig({
  app: {
    head: {
      charset: "utf-8",
      viewport: "width=device-width, initial-scale=1",
      title: "Daedalus",
      script:[{
        src:" https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1227600212000715",
        async:true,
        crossorigin:'anonymous'
      }],
      meta: [
        { name: "keywords", content: "HTML, CSS, JavaScript, Vue.js, Nuxt.js" },
        { name: "author", content: "Paweł Kiciński" },
      ],

    },
  },
  i18n: {
    locales: [
      "af-ZA",
      "ar-AE",
      "ar-BH",
      "ar-EG",
      "ar-IQ",
      "ar-JO",
      "ar-LY",
      "ar-MA",
      "ar-QA",
      "ar-SA",
      "ar-TD",
      "ar-YE",
      "be-BY",
      "bg-BG",
      "bn-BD",
      "br-FR",
      "ca-AD",
      "ca-ES",
      "ch-GU",
      "cs-CZ",
      "cy-GB",
      "da-DK",
      "de-AT",
      "de-CH",
      "de-DE",
      "el-CY",
      "el-GR",
      "en-AG",
      "en-AU",
      "en-BB",
      "en-BZ",
      "en-CA",
      "en-CM",
      "en-GB",
      "en-GG",
      "en-GH",
      "en-GI",
      "en-GY",
      "en-IE",
      "en-JM",
      "en-KE",
      "en-LC",
      "en-MW",
      "en-NZ",
      "en-PG",
      "en-TC",
      "en-US",
      "en-ZM",
      "en-ZW",
      "eo-EO",
      "es-AR",
      "es-CL",
      "es-DO",
      "es-EC",
      "es-ES",
      "es-GQ",
      "es-GT",
      "es-HN",
      "es-MX",
      "es-NI",
      "es-PA",
      "es-PE",
      "es-PY",
      "es-SV",
      "es-UY",
      "et-EE",
      "eu-ES",
      "fa-IR",
      "fi-FI",
      "fr-BF",
      "fr-CA",
      "fr-CD",
      "fr-CI",
      "fr-FR",
      "fr-GF",
      "fr-GP",
      "fr-MC",
      "fr-ML",
      "fr-MU",
      "fr-PF",
      "ga-IE",
      "gd-GB",
      "gl-ES",
      "he-IL",
      "hi-IN",
      "hr-HR",
      "hu-HU",
      "id-ID",
      "it-IT",
      "it-VA",
      "ja-JP",
      "ka-GE",
      "kk-KZ",
      "kn-IN",
      "ko-KR",
      "ku-TR",
      "ky-KG",
      "lt-LT",
      "lv-LV",
      "ml-IN",
      "mr-IN",
      "ms-MY",
      "ms-SG",
      "nb-NO",
      "nl-BE",
      "nl-NL",
      "no-NO",
      "pa-IN",
      "pl-PL",
      "pt-AO",
      "pt-BR",
      "pt-MZ",
      "pt-PT",
      "ro-MD",
      "ro-RO",
      "ru-RU",
      "si-LK",
      "sk-SK",
      "sl-SI",
      "so-SO",
      "sq-AL",
      "sq-XK",
      "sr-ME",
      "sr-RS",
      "sv-SE",
      "sw-TZ",
      "ta-IN",
      "te-IN",
      "th-TH",
      "tl-PH",
      "tr-TR",
      "uk-UA",
      "ur-PK",
      "uz-UZ",
      "vi-VN",
      "zh-CN",
      "zh-HK",
      "zh-SG",
      "zh-TW",
      "zu-ZA"
    ],
    
    strategy:'no_prefix',
    defaultLocale: "en-GB",
    detectBrowserLanguage: false
  },
vite:{
  css:{
    preprocessorOptions:{
      scss:{
        api: 'modern-compiler'
      }
    }
  }
},
  nitro: {
    compressPublicAssets: true,
  },

  modules: ["@nuxt/image",  '@vueuse/nuxt','@nuxtjs/i18n'],

  routeRules: {
    "/": { prerender: true },
  },

  css: ["~/assets/main.css", "~/assets/base.css"],

  components: [
    {
      path: "~/components",
      pathPrefix: false,
    },
  ],

  dev: true,

  runtimeConfig: {
    apiSecret: "",
    apiLink: "",

    imgLink: "",
    firebaseAdmin: {
      projectId: process.env.FIREBASE_SA_PROJECT_ID,

      privateKey: process.env.FIREBASE_PRIVATE_SA_KEY
        ? process.env.FIREBASE_PRIVATE_SA_KEY.replace(/\\n/gm, "\n")
        : undefined,
      clientEmail: process.env.FIREBASE_SA_CLIENT_EMAIL,
    },
    public: {
      firebase: {
        apiKey: process.env.FIREBASE_API_KEY,
        authDomain: process.env.FIREBASE_AUTH_DOMAIN,
        databaseURL: process.env.FIREBASE_DATABASE,
        projectId: process.env.FIREBASE_PROJECT_ID,
        storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
        messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
        appId: process.env.FIREBASE_APP_ID,
        measurementId: process.env.FIREBASE_MEASUREMENT_ID,
      },
      apiBase: "/api",
    },
  },

  compatibilityDate: "2024-10-26",
});